version: '3.3'

networks:
  www-external:
    internal: false
  www-internal:
    internal: true

services:
  elasticsearch:
    build: elasticsearch/.
    container_name: elasticsearch
    env_file:
      - "elasticsearch/elasticsearch.env"
      - "elasticsearch/elasticsearch-${ENV:-local}.env"
    image: elasticsearch:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
  httpd:
    build: httpd/.
    container_name: httpd
    env_file:
      - "httpd/httpd.env"
      - "httpd/httpd-${ENV:-local}.env"
    image: httpd:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "httpd:/var/www/html"
  liferay:
    build:
      args:
        BUILD_SCRIPTS: "bundle-exclude.sh,apply-fix-packs.sh"
        BUNDLE_URL: "http://files.liferay.com/private/ee/portal/7.0.10/liferay-dxp-digital-enterprise-tomcat-7.0-ga1-20160617092557801.zip"
        JAVA_PACKAGE: "openjdk8"
        LICENSE_URL: "http://files.liferay.com/private/ee/liferay-up/License/7.0/license.xml"
        PATCH_URLS: "http://files.liferay.com/private/ee/fix-packs/7.0.10/de/liferay-fix-pack-de-44-7010.zip"
      context: liferay/.
    container_name: liferay
    depends_on:
      - "elasticsearch"
      - "mariadb"
    env_file:
      - "liferay/liferay.env"
      - "liferay/liferay-${ENV:-local}.env"
    image: liferay:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8000:8000"
      - "11311:11311"
      - "12345:12345"
    user: liferay
    volumes:
      - "liferay:/opt/java/liferay/data"
      - "../extensions/wcm-deployment/wcm-deployment-service/src/main/resources:/mnt/wcm"
      - "./liferay/resources/deploy:/opt/java/liferay/deploy"
      - "./liferay/resources/osgi/modules:/opt/java/liferay/osgi/modules"
      - "./liferay/resources/osgi/war:/opt/java/liferay/osgi/war"
  mariadb:
    build: mariadb/.
    container_name: mariadb
    env_file:
      - "mariadb/mariadb.env"
      - "mariadb/mariadb-${ENV:-local}.env"
    image: mariadb:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "3307:3306"
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./mariadb/resources/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/"

volumes:
  elasticsearch:
  httpd:
  liferay:
  mariadb:
